/** @type {import('next').NextConfig} */
const nextConfig = {
  // Static export is generated by `next build` when output is set to `export`.
  output: "export",
  // Ensure Turbopack uses an absolute project root across environments.
  turbopack: {
    root: __dirname,
  },
};

module.exports = nextConfig;
