from __future__ import annotations

import os
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

from flask import Flask, jsonify, render_template, request

from db import db_connect, db_execute, fetch_value, is_sqlite_connection, listings_table_exists

BASE_DIR = Path(__file__).resolve().parent
DEFAULT_DB_PATH = BASE_DIR / "kleinanzeigen_listings.db"
EMAIL_PATTERN = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")
FREQUENCY_DAYS = {
    "daily": 1,
    "weekly": 7,
    "biweekly": 14,
    "monthly": 30,
}

app = Flask(__name__)


def initialize_user_subscription_table(connection) -> None:
    subscription_id_definition = (
        "INTEGER PRIMARY KEY AUTOINCREMENT"
        if is_sqlite_connection(connection)
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )

    db_execute(
        connection,
        f"""
        CREATE TABLE IF NOT EXISTS user_subscriptions (
            subscription_id {subscription_id_definition},
            email TEXT NOT NULL UNIQUE,
            frequency TEXT NOT NULL DEFAULT 'weekly',
            max_price_eur INTEGER NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_sent_at TEXT,
            next_send_at TEXT NOT NULL
        )
        """
    )
    db_execute(
        connection,
        "CREATE INDEX IF NOT EXISTS idx_user_subscriptions_next_send ON user_subscriptions(next_send_at)",
    )
    connection.commit()


def is_valid_email(email: str) -> bool:
    return EMAIL_PATTERN.match(email.strip()) is not None


def next_send_timestamp(frequency: str) -> str:
    days = FREQUENCY_DAYS.get(frequency, 7)
    return (datetime.now(timezone.utc) + timedelta(days=days)).isoformat(timespec="seconds")


@app.route("/")
def index() -> str:
    return render_template("index.html")


@app.route("/subscriptions/manage")
def subscriptions_manage() -> str:
    return render_template("subscriptions.html")


@app.route("/api/meta", methods=["GET"])
def api_meta():
    with db_connect(DEFAULT_DB_PATH) as connection:
        initialize_user_subscription_table(connection)

        listings_count = 0
        avg_price = None
        min_price = None
        max_price = None
        latest = None

        if listings_table_exists(connection):
            listings_count = fetch_value(db_execute(connection, "SELECT COUNT(*) AS c FROM listings").fetchone(), "c")
            price_row = db_execute(
                connection,
                "SELECT AVG(price_eur) AS avg_price, MIN(price_eur) AS min_price, MAX(price_eur) AS max_price FROM listings"
            ).fetchone()
            latest = fetch_value(db_execute(connection, "SELECT MAX(created_at) AS latest FROM listings").fetchone(), "latest")
            avg_price = fetch_value(price_row, "avg_price")
            min_price = fetch_value(price_row, "min_price")
            max_price = fetch_value(price_row, "max_price")

        stats_rows = db_execute(
            connection,
            """
            SELECT frequency, COUNT(*) AS cnt
            FROM user_subscriptions
            WHERE is_active = 1
            GROUP BY frequency
            """
        ).fetchall()

    stats = {fetch_value(row, "frequency"): int(fetch_value(row, "cnt")) for row in stats_rows}
    return jsonify(
        {
            "dbPath": os.getenv("DATABASE_URL", os.getenv("DB_PATH", str(DEFAULT_DB_PATH))),
            "listingsCount": int(listings_count),
            "avgPrice": int(avg_price) if avg_price else None,
            "minPrice": int(min_price) if min_price else None,
            "maxPrice": int(max_price) if max_price else None,
            "latestCrawl": latest,
            "subscriptionStats": stats,
        }
    )


@app.route("/api/preview", methods=["GET"])
def api_preview():
    max_price = request.args.get("max_price", type=int)
    limit = request.args.get("limit", default=20, type=int)

    if max_price is None or max_price <= 0:
        return jsonify({"error": "max_price muss als positive Zahl gesetzt werden."}), 400

    with db_connect(DEFAULT_DB_PATH) as connection:
        if not listings_table_exists(connection):
            return jsonify({"rows": []})

        rows = db_execute(
            connection,
            """
            SELECT listing_id, title, price_eur, location, created_at, url
            FROM listings
            WHERE price_eur <= %s
            ORDER BY created_at DESC
            LIMIT %s
            """,
            (max_price, max(1, min(limit, 100))),
        ).fetchall()

    data = [dict(row) for row in rows]
    return jsonify({"rows": data})


@app.route("/api/subscription", methods=["POST"])
def api_subscription_upsert():
    payload = request.get_json(silent=True) or {}
    email = str(payload.get("email", "")).strip().lower()
    frequency = str(payload.get("frequency", "weekly")).strip().lower()
    max_price = payload.get("maxPriceEur")

    if not is_valid_email(email):
        return jsonify({"error": "Bitte gueltige E-Mail-Adresse angeben."}), 400
    if frequency not in FREQUENCY_DAYS:
        return jsonify({"error": "Ungueltige Frequenz."}), 400
    if not isinstance(max_price, int) or max_price < 50000:
        return jsonify({"error": "maxPriceEur muss eine ganze Zahl >= 50000 sein."}), 400

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    next_send_at = next_send_timestamp(frequency)

    with db_connect(DEFAULT_DB_PATH) as connection:
        initialize_user_subscription_table(connection)
        db_execute(
            connection,
            """
            INSERT INTO user_subscriptions (
                email,
                frequency,
                max_price_eur,
                is_active,
                created_at,
                updated_at,
                next_send_at
            )
            VALUES (%s, %s, %s, 1, %s, %s, %s)
            ON CONFLICT(email) DO UPDATE SET
                frequency = excluded.frequency,
                max_price_eur = excluded.max_price_eur,
                is_active = 1,
                updated_at = excluded.updated_at,
                next_send_at = excluded.next_send_at
            """,
            (email, frequency, max_price, timestamp, timestamp, next_send_at),
        )
        connection.commit()

    return jsonify(
        {
            "message": "Abo gespeichert.",
            "subscription": {
                "email": email,
                "frequency": frequency,
                "maxPriceEur": max_price,
                "nextSendAt": next_send_at,
            },
        }
    )


@app.route("/api/subscription", methods=["GET"])
def api_subscription_get():
    email = request.args.get("email", default="", type=str).strip().lower()
    if not is_valid_email(email):
        return jsonify({"error": "Bitte gueltige E-Mail-Adresse angeben."}), 400

    with db_connect(DEFAULT_DB_PATH) as connection:
        initialize_user_subscription_table(connection)
        row = db_execute(
            connection,
            """
            SELECT email, frequency, max_price_eur, updated_at, next_send_at
            FROM user_subscriptions
            WHERE email = %s AND is_active = 1
            """,
            (email,),
        ).fetchone()

    if row is None:
        return jsonify({"subscription": None})

    return jsonify(
        {
            "subscription": {
                "email": fetch_value(row, "email"),
                "frequency": fetch_value(row, "frequency"),
                "maxPriceEur": fetch_value(row, "max_price_eur"),
                "updatedAt": fetch_value(row, "updated_at"),
                "nextSendAt": fetch_value(row, "next_send_at"),
            }
        }
    )


@app.route("/api/subscriptions", methods=["GET"])
def api_subscriptions_list():
    with db_connect(DEFAULT_DB_PATH) as connection:
        initialize_user_subscription_table(connection)
        rows = db_execute(
            connection,
            """
            SELECT subscription_id, email, frequency, max_price_eur, updated_at, next_send_at
            FROM user_subscriptions
            WHERE is_active = 1
            ORDER BY updated_at DESC
            """
        ).fetchall()

    return jsonify(
        {
            "subscriptions": [
                {
                    "subscriptionId": fetch_value(row, "subscription_id"),
                    "email": fetch_value(row, "email"),
                    "frequency": fetch_value(row, "frequency"),
                    "maxPriceEur": fetch_value(row, "max_price_eur"),
                    "updatedAt": fetch_value(row, "updated_at"),
                    "nextSendAt": fetch_value(row, "next_send_at"),
                }
                for row in rows
            ]
        }
    )


@app.route("/api/subscription", methods=["DELETE"])
def api_subscription_delete():
    email = request.args.get("email", default="", type=str).strip().lower()
    if not is_valid_email(email):
        return jsonify({"error": "Bitte gueltige E-Mail-Adresse angeben."}), 400

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")

    with db_connect(DEFAULT_DB_PATH) as connection:
        initialize_user_subscription_table(connection)
        result = db_execute(
            connection,
            """
            UPDATE user_subscriptions
            SET is_active = 0,
                updated_at = %s
            WHERE email = %s
              AND is_active = 1
            """,
            (timestamp, email),
        )
        connection.commit()

    if result.rowcount == 0:
        return jsonify({"error": "Kein aktives Abo gefunden."}), 404

    return jsonify({"message": "Abo deaktiviert.", "email": email})


if __name__ == "__main__":
    app.run(debug=os.getenv("FLASK_DEBUG", "0") == "1")
