from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path

import psycopg

BASE_DIR = Path(__file__).resolve().parent
DEFAULT_SQLITE_PATH = BASE_DIR / "kleinanzeigen_listings.db"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migriert Daten von SQLite nach PostgreSQL.")
    parser.add_argument(
        "--sqlite",
        default=os.getenv("DB_PATH", str(DEFAULT_SQLITE_PATH)),
        help="Pfad zur SQLite-Datenbank",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="Batch-Groesse fuer den Transfer",
    )
    return parser.parse_args()


def ensure_postgres_schema(pg_conn) -> None:
    pg_conn.execute(
        """
        CREATE TABLE IF NOT EXISTS listings (
            listing_id TEXT PRIMARY KEY,
            title TEXT,
            price_eur INTEGER,
            area_sqm REAL,
            rooms REAL,
            location TEXT,
            url TEXT,
            description TEXT,
            created_at TEXT NOT NULL,
            valuation_model TEXT,
            valuation_run_at TEXT,
            est_cold_rent_sqm REAL,
            est_cold_rent_monthly REAL,
            est_cold_rent_min_monthly REAL,
            est_cold_rent_max_monthly REAL,
            gross_yield_pct REAL,
            price_to_rent_factor REAL,
            valuation_confidence REAL,
            valuation_note TEXT,
            listing_quality_index REAL,
            listing_quality_grade TEXT,
            listing_quality_note TEXT,
            ai_rating_model TEXT,
            ai_rating_run_at TEXT,
            ai_rating_score REAL,
            ai_rating_reason TEXT,
            ai_rating_error TEXT
        )
        """
    )
    pg_conn.execute("CREATE INDEX IF NOT EXISTS idx_listings_price ON listings(price_eur)")
    pg_conn.execute("CREATE INDEX IF NOT EXISTS idx_listings_location ON listings(location)")

    pg_conn.execute(
        """
        CREATE TABLE IF NOT EXISTS crawler_state (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    pg_conn.execute(
        """
        CREATE TABLE IF NOT EXISTS user_subscriptions (
            subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            frequency TEXT NOT NULL DEFAULT 'weekly',
            max_price_eur INTEGER NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_sent_at TEXT,
            next_send_at TEXT NOT NULL
        )
        """
    )
    pg_conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_user_subscriptions_next_send ON user_subscriptions(next_send_at)"
    )


def migrate_listings(sqlite_conn, pg_conn, batch_size: int) -> int:
    rows = sqlite_conn.execute("SELECT * FROM listings").fetchall()
    if not rows:
        return 0

    columns = [description[0] for description in sqlite_conn.execute("SELECT * FROM listings LIMIT 1").description]
    col_sql = ", ".join(columns)
    placeholders = ", ".join(["%s"] * len(columns))
    update_sql = ", ".join([f"{column}=EXCLUDED.{column}" for column in columns if column != "listing_id"])

    query = f"""
        INSERT INTO listings ({col_sql})
        VALUES ({placeholders})
        ON CONFLICT (listing_id) DO UPDATE SET {update_sql}
    """

    migrated = 0
    for index in range(0, len(rows), batch_size):
        chunk = rows[index : index + batch_size]
        values = [tuple(row[column] for column in columns) for row in chunk]
        with pg_conn.cursor() as cursor:
            cursor.executemany(query, values)
        migrated += len(chunk)
    return migrated


def migrate_crawler_state(sqlite_conn, pg_conn) -> int:
    rows = sqlite_conn.execute("SELECT key, value, updated_at FROM crawler_state").fetchall()
    if not rows:
        return 0

    with pg_conn.cursor() as cursor:
        cursor.executemany(
            """
            INSERT INTO crawler_state (key, value, updated_at)
            VALUES (%s, %s, %s)
            ON CONFLICT (key) DO UPDATE SET
                value = EXCLUDED.value,
                updated_at = EXCLUDED.updated_at
            """,
            [(row["key"], row["value"], row["updated_at"]) for row in rows],
        )
    return len(rows)


def migrate_subscriptions(sqlite_conn, pg_conn) -> int:
    rows = sqlite_conn.execute(
        """
        SELECT
            subscription_id,
            email,
            frequency,
            max_price_eur,
            is_active,
            created_at,
            updated_at,
            last_sent_at,
            next_send_at
        FROM user_subscriptions
        """
    ).fetchall()

    if not rows:
        return 0

    with pg_conn.cursor() as cursor:
        cursor.executemany(
            """
            INSERT INTO user_subscriptions (
                subscription_id,
                email,
                frequency,
                max_price_eur,
                is_active,
                created_at,
                updated_at,
                last_sent_at,
                next_send_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (email) DO UPDATE SET
                frequency = EXCLUDED.frequency,
                max_price_eur = EXCLUDED.max_price_eur,
                is_active = EXCLUDED.is_active,
                updated_at = EXCLUDED.updated_at,
                last_sent_at = EXCLUDED.last_sent_at,
                next_send_at = EXCLUDED.next_send_at
            """,
            [
                (
                    row["subscription_id"],
                    row["email"],
                    row["frequency"],
                    row["max_price_eur"],
                    row["is_active"],
                    row["created_at"],
                    row["updated_at"],
                    row["last_sent_at"],
                    row["next_send_at"],
                )
                for row in rows
            ],
        )
    return len(rows)


def main() -> int:
    args = parse_args()
    sqlite_path = Path(args.sqlite).expanduser()

    database_url = os.getenv("DATABASE_URL", "").strip()
    if not database_url:
        print("DATABASE_URL fehlt. Bitte auf PostgreSQL-URL setzen.")
        return 1

    if not sqlite_path.exists():
        print(f"SQLite-Datei nicht gefunden: {sqlite_path}")
        return 1

    with sqlite3.connect(str(sqlite_path)) as sqlite_conn, psycopg.connect(database_url) as pg_conn:
        sqlite_conn.row_factory = sqlite3.Row
        ensure_postgres_schema(pg_conn)

        listings_count = migrate_listings(sqlite_conn, pg_conn, args.batch_size)
        crawler_state_count = migrate_crawler_state(sqlite_conn, pg_conn)
        subscriptions_count = migrate_subscriptions(sqlite_conn, pg_conn)

        pg_conn.commit()

    print(f"Migriert: listings={listings_count}, crawler_state={crawler_state_count}, user_subscriptions={subscriptions_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
