#!/usr/bin/env python
"""
Interaktives Setup-Skript für SQLite zu PostgreSQL Migration.
Dieses Skript hilft Ihnen, die Datenbank auf Render zu migrieren.
"""
from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

try:
    import psycopg
except ImportError:
    print("❌ Fehler: psycopg ist nicht installiert. Bitte installieren Sie die requirements:")
    print("   pip install -r requirements.txt")
    sys.exit(1)


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_SQLITE_PATH = BASE_DIR / "kleinanzeigen_listings.db"


def get_database_url_from_input() -> str:
    """Fordert den Benutzer auf, die DATABASE_URL einzugeben."""
    print("\n" + "=" * 80)
    print("RENDER DATENBANK-SETUP")
    print("=" * 80)
    print("\n📋 Um die DATABASE_URL zu finden:")
    print("   1. Gehen Sie zu https://dashboard.render.com")
    print("   2. Wählen Sie 'Databases' → 'Immo-DB'")
    print("   3. Kopieren Sie die 'External Database URL'")
    print("   4. Fügen Sie diese hier ein")
    print("\n")

    database_url = input("🔑 Geben Sie die DATABASE_URL ein: ").strip()

    if not database_url:
        print("❌ Fehler: DATABASE_URL darf nicht leer sein")
        sys.exit(1)

    if not database_url.startswith("postgresql://"):
        print("❌ Fehler: Ungültiges URL-Format. Sollte mit 'postgresql://' beginnen")
        sys.exit(1)

    return database_url


def test_postgres_connection(database_url: str) -> bool:
    """Testet die Verbindung zur PostgreSQL-Datenbank."""
    try:
        with psycopg.connect(database_url) as conn:
            with conn.cursor() as cursor:
                cursor.execute("SELECT 1")
            print("✅ Verbindung zu PostgreSQL erfolgreich")
            return True
    except Exception as e:
        print(f"❌ Fehler beim Verbindungstest: {e}")
        return False


def create_postgres_schema(database_url: str) -> None:
    """Erstellt die PostgreSQL-Tabellen."""
    with psycopg.connect(database_url) as conn:
        with conn.cursor() as cursor:
            print("\n📋 Erstelle PostgreSQL-Schema...")

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS listings (
                    listing_id TEXT PRIMARY KEY,
                    title TEXT,
                    price_eur INTEGER,
                    area_sqm REAL,
                    rooms REAL,
                    location TEXT,
                    url TEXT,
                    description TEXT,
                    created_at TEXT NOT NULL,
                    valuation_model TEXT,
                    valuation_run_at TEXT,
                    est_cold_rent_sqm REAL,
                    est_cold_rent_monthly REAL,
                    est_cold_rent_min_monthly REAL,
                    est_cold_rent_max_monthly REAL,
                    gross_yield_pct REAL,
                    price_to_rent_factor REAL,
                    valuation_confidence REAL,
                    valuation_note TEXT,
                    listing_quality_index REAL,
                    listing_quality_grade TEXT,
                    listing_quality_note TEXT,
                    ai_rating_model TEXT,
                    ai_rating_run_at TEXT,
                    ai_rating_score REAL,
                    ai_rating_reason TEXT,
                    ai_rating_error TEXT
                )
                """
            )
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_listings_price ON listings(price_eur)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_listings_location ON listings(location)")

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS crawler_state (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS user_subscriptions (
                    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email TEXT NOT NULL UNIQUE,
                    frequency TEXT NOT NULL DEFAULT 'weekly',
                    max_price_eur INTEGER NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    last_sent_at TEXT,
                    next_send_at TEXT NOT NULL
                )
                """
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_user_subscriptions_next_send ON user_subscriptions(next_send_at)"
            )

            conn.commit()
            print("✅ PostgreSQL-Schema erstellt")


def migrate_data(sqlite_path: str, database_url: str, batch_size: int = 500) -> None:
    """Migriert Daten von SQLite zu PostgreSQL."""
    sqlite_path_obj = Path(sqlite_path)

    if not sqlite_path_obj.exists():
        print(f"⚠️  Warnung: SQLite-Datei nicht gefunden: {sqlite_path}")
        return

    print(f"\n📦 Migriere Daten von SQLite nach PostgreSQL...")
    print(f"   SQLite: {sqlite_path}")

    sqlite_conn = sqlite3.connect(str(sqlite_path))
    sqlite_conn.row_factory = sqlite3.Row

    with psycopg.connect(database_url) as pg_conn:
        # Migriere Listings
        try:
            rows = sqlite_conn.execute("SELECT * FROM listings").fetchall()
            if rows:
                columns = [description[0] for description in sqlite_conn.execute("SELECT * FROM listings LIMIT 1").description]
                col_sql = ", ".join(columns)
                placeholders = ", ".join(["%s"] * len(columns))
                update_sql = ", ".join([f"{column}=EXCLUDED.{column}" for column in columns if column != "listing_id"])

                query = f"""
                    INSERT INTO listings ({col_sql})
                    VALUES ({placeholders})
                    ON CONFLICT (listing_id) DO UPDATE SET {update_sql}
                """

                migrated = 0
                with pg_conn.cursor() as cursor:
                    for index in range(0, len(rows), batch_size):
                        chunk = rows[index : index + batch_size]
                        values = [tuple(row[column] for column in columns) for row in chunk]
                        cursor.executemany(query, values)
                        migrated += len(chunk)
                    pg_conn.commit()

                print(f"   ✅ {migrated} Listings migriert")
        except Exception as e:
            print(f"   ⚠️  Keine Listings zum Migrieren oder Fehler: {e}")

        # Migriere Crawler State
        try:
            rows = sqlite_conn.execute("SELECT * FROM crawler_state").fetchall()
            if rows:
                with pg_conn.cursor() as cursor:
                    cursor.executemany(
                        """
                        INSERT INTO crawler_state (key, value, updated_at)
                        VALUES (%s, %s, %s)
                        ON CONFLICT (key) DO UPDATE SET
                            value = EXCLUDED.value,
                            updated_at = EXCLUDED.updated_at
                        """,
                        [(row["key"], row["value"], row["updated_at"]) for row in rows],
                    )
                    pg_conn.commit()
                print(f"   ✅ {len(rows)} Crawler States migriert")
        except Exception as e:
            print(f"   ⚠️  Keine Crawler States zum Migrieren oder Fehler: {e}")

        # Migriere Subscriptions
        try:
            rows = sqlite_conn.execute(
                """
                SELECT
                    subscription_id,
                    email,
                    frequency,
                    max_price_eur,
                    is_active,
                    created_at,
                    updated_at,
                    last_sent_at,
                    next_send_at
                FROM user_subscriptions
                """
            ).fetchall()
            if rows:
                with pg_conn.cursor() as cursor:
                    cursor.executemany(
                        """
                        INSERT INTO user_subscriptions (
                            subscription_id,
                            email,
                            frequency,
                            max_price_eur,
                            is_active,
                            created_at,
                            updated_at,
                            last_sent_at,
                            next_send_at
                        )
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                        ON CONFLICT (email) DO UPDATE SET
                            frequency = EXCLUDED.frequency,
                            max_price_eur = EXCLUDED.max_price_eur,
                            is_active = EXCLUDED.is_active,
                            updated_at = EXCLUDED.updated_at,
                            last_sent_at = EXCLUDED.last_sent_at,
                            next_send_at = EXCLUDED.next_send_at
                        """,
                        [
                            (
                                row["subscription_id"],
                                row["email"],
                                row["frequency"],
                                row["max_price_eur"],
                                row["is_active"],
                                row["created_at"],
                                row["updated_at"],
                                row["last_sent_at"],
                                row["next_send_at"],
                            )
                            for row in rows
                        ],
                    )
                    pg_conn.commit()
                print(f"   ✅ {len(rows)} Subscriptions migriert")
        except Exception as e:
            print(f"   ⚠️  Keine Subscriptions zum Migrieren oder Fehler: {e}")

    sqlite_conn.close()
    print("✅ Datenmigration abgeschlossen")


def save_env_file(database_url: str) -> None:
    """Speichert die DATABASE_URL in einer .env.production Datei."""
    env_file = BASE_DIR / ".env.production"
    with open(env_file, "w") as f:
        f.write(f"DATABASE_URL={database_url}\n")
    print(f"\n📝 DATABASE_URL gespeichert in: {env_file}")


def main():
    print("\n🚀 SQLite zu PostgreSQL Migration Tool")
    print("=" * 80)

    # Prüfe, ob DATABASE_URL in der Umgebung ist
    database_url = os.getenv("DATABASE_URL", "").strip()

    if not database_url:
        database_url = get_database_url_from_input()

    # Teste die Verbindung
    print("\n🔗 Teste Verbindung zur PostgreSQL-Datenbank...")
    if not test_postgres_connection(database_url):
        sys.exit(1)

    # Erstelle das Schema
    try:
        create_postgres_schema(database_url)
    except Exception as e:
        print(f"❌ Fehler beim Erstellen des Schemas: {e}")
        sys.exit(1)

    # Migriere die Daten
    try:
        sqlite_path = os.getenv("DB_PATH", str(DEFAULT_SQLITE_PATH))
        migrate_data(sqlite_path, database_url)
    except Exception as e:
        print(f"❌ Fehler bei der Datenmigration: {e}")
        sys.exit(1)

    # Speichere die DATABASE_URL
    save_env_file(database_url)

    print("\n" + "=" * 80)
    print("✅ MIGRATION ERFOLGREICH ABGESCHLOSSEN!")
    print("=" * 80)
    print("\n📖 Nächste Schritte:")
    print("   1. Pushen Sie Ihre Änderungen zu GitHub")
    print("   2. Gehen Sie zu https://dashboard.render.com/blueprints")
    print("   3. Verbinden Sie Ihr Repository und deployen Sie")
    print("   4. Setzen Sie die DATABASE_URL Umgebungsvariable in den Services")
    print("\n")


if __name__ == "__main__":
    main()
