"""
Setup-Skript für PostgreSQL-Datenbank.
Erstellt alle notwendigen Tabellen und Indizes.
"""
from __future__ import annotations

import os
import sys

import psycopg


def ensure_postgres_schema(pg_conn) -> None:
    """Erstellt alle notwendigen Tabellen in PostgreSQL."""
    with pg_conn.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS listings (
                listing_id TEXT PRIMARY KEY,
                title TEXT,
                price_eur INTEGER,
                area_sqm REAL,
                rooms REAL,
                location TEXT,
                url TEXT,
                description TEXT,
                created_at TEXT NOT NULL,
                valuation_model TEXT,
                valuation_run_at TEXT,
                est_cold_rent_sqm REAL,
                est_cold_rent_monthly REAL,
                est_cold_rent_min_monthly REAL,
                est_cold_rent_max_monthly REAL,
                gross_yield_pct REAL,
                price_to_rent_factor REAL,
                valuation_confidence REAL,
                valuation_note TEXT,
                listing_quality_index REAL,
                listing_quality_grade TEXT,
                listing_quality_note TEXT,
                ai_rating_model TEXT,
                ai_rating_run_at TEXT,
                ai_rating_score REAL,
                ai_rating_reason TEXT,
                ai_rating_error TEXT
            )
            """
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_listings_price ON listings(price_eur)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_listings_location ON listings(location)")

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS crawler_state (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS user_subscriptions (
                subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                frequency TEXT NOT NULL DEFAULT 'weekly',
                max_price_eur INTEGER NOT NULL,
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                last_sent_at TEXT,
                next_send_at TEXT NOT NULL
            )
            """
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_user_subscriptions_next_send ON user_subscriptions(next_send_at)"
        )

        pg_conn.commit()
        print("✅ PostgreSQL-Schema erfolgreich erstellt")


def main():
    database_url = os.getenv("DATABASE_URL", "").strip()

    if not database_url:
        print("❌ Fehler: DATABASE_URL Umgebungsvariable ist nicht gesetzt")
        sys.exit(1)

    try:
        with psycopg.connect(database_url) as conn:
            ensure_postgres_schema(conn)
            print("✅ Setup erfolgreich abgeschlossen")
    except psycopg.Error as e:
        print(f"❌ Fehler beim Datenbankzugriff: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
